### ISSUE TITLE
Does it work in the latest version?

### ISSUE THREAD

**Issue by mynameisbogdan** [Caedis/plex-auto-skip-intro#2]
Hello @Caedis,

I tried your mod and it doesn't seem to work on the latest version. It still shows the `Skip intro` button as usual, but that's it. 

I doubled check that your mod is in fact modifying the JS file and it does.

Does it need any particular setting to be enabled/disabled?

Plex version: `ghcr.io/linuxserver/plex:1.27.0` (I'm using the `:latest` tag)

**Comment by cjmanca** [comment]
Plex removed the "Advertise as player" option in the latest version unfortunately, which is required for the script to work. The only solution right now that I'm aware of is to downgrade your player to the previous version.

**Comment by mynameisbogdan** [comment]
Sadly even if you downgrade, the player will update itself on the next run. At least this is what happens on mac.

**Comment by cjmanca** [comment]
I don't know about mac, but I set the permissions on the updates folder to deny writing to everyone and it worked for me.

On windows, the updates folder is:
C:\Users\[username]\AppData\Local\Plex\cache\updates

**Comment by drumstick77** [comment]
hiya, so is this mods actually working on the latest version? if anyone can please confirm, then that'd be great. thanks
