### ISSUE TITLE
is this mod actually working on the latest docker plex version? Thanks

### ISSUE THREAD

**Issue by drumstick77** [Caedis/plex-auto-skip-intro#4]
I've added this under the environment
- DOCKER_MODS=caedis/plex-auto-skip-intro
but it is still not skipping automatically.
if someone can please confirm if it's actually working with the latest version, then that'd be great. thanks

**Comment by i-am-at0m** [comment]
> I've added this under the environment
> - DOCKER_MODS=caedis/plex-auto-skip-intro
> but it is still not skipping automatically.
> if someone can please confirm if it's actually working with the latest version, then that'd be great. thanks

Which container are you using? Looks like this one only works with the LinuxServer one, not the BinHex one (like I use :( )

Reading the source, it only works on the self hosted web client, too. Not native clients, and not the client served by Plex.tv

**Comment by drumstick77** [comment]
yeah, I'm using linuxserver/plex image.
Ah okay, so it only works with self hosted webclient? as local IP:32400 of the server?

**Comment by i-am-at0m** [comment]
> yeah, I'm using linuxserver/plex image.
> Ah okay, so it only works with self hosted webclient? as local IP:32400 of the server?

I'm not certain as I haven't used it myself but reading the source that's how it looks like it works yes
